version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: webpack
    versions:
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.27.1
    - 5.28.0
    - 5.30.0
    - 5.31.2
  - dependency-name: css-loader
    versions:
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: mapbox-gl
    versions:
    - 2.1.1
    - 2.2.0
  - dependency-name: react
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: "@amaurymartiny/config"
    versions:
    - 1.3.4
